### PR TITLE
example-go at scale

### PR DESCRIPTION
**Pull request by rbucker**
experience the scale process and verify with the hostname and other environment vars.

### CODE REVIEW

**Comment by mboersma** [comment]
This is great--apologies for not noticing this PR before @rbucker. Although `os.Hostname()` doesn't return what I expected locally--looks like a container id?
```Release v3 Powered by Deis on 36ea55158a3e```

**Comment by bacongobbler** [comment]
This is great... But it may break the integration tests. :(

> Although os.Hostname() doesn't return what I expected locally--looks like a container id?

Yes, that is the expected behaviour unless you run the container with `--hostname`: https://docs.docker.com/articles/networking/#dns

**Comment by mboersma** [comment]
I updated the output in #7 to address @bacongobbler's comment--tests might do a `strings.HasPrefix()` which would fail, and there's another example app that added a second line of output, so there's precedent for that. Thanks again @rbucker!

**Comment by rbucker** [comment]
sorry I could not be of more help.

**Comment by mboersma** [comment]
Not at all--we appreciate it and, and apologies for not following up on this when you originally submitted it.

**Pull request closed without merging**
